# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fB0tAHphQ6lGR8oo9iAM6_ITmuFIU92l
"""

import streamlit as st
import pandas as pd
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import math

# --- CONFIGURAÇÃO DA PÁGINA WEB ---
st.set_page_config(
    page_title="Painel de Rematrículas",
    layout="wide",
    initial_sidebar_state="collapsed"
)

# --- FUNÇÃO DE CARREGAMENTO (COM CACHE AUTOMÁTICO) ---
# O TTL=300 significa que ele atualiza os dados a cada 300 segundos (5 min) automaticamente
@st.cache_data(ttl=300)
def carregar_dados():
    sheet_id = "1ZxdCsSIjGY0h4DBgtc7CBsPGSG3dvDLRdTNv_vlxgYw"
    url = f"https://docs.google.com/spreadsheets/d/{sheet_id}/export?format=csv"
    try:
        return pd.read_csv(url)
    except Exception as e:
        st.error(f"Erro de conexão com a planilha: {e}")
        return pd.DataFrame()

# --- INTERFACE E BOTÃO DE ATUALIZAR ---
col1, col2 = st.columns([8, 1])
with col1:
    st.markdown("### 📊 Monitoramento em Tempo Real")
with col2:
    if st.button("🔄 Atualizar"):
        st.cache_data.clear()
        st.rerun()

# --- LÓGICA DE PROCESSAMENTO ---
df = carregar_dados()

if not df.empty:
    # 1. Tratamento
    df.columns = df.columns.str.strip().str.upper()
    col_unidade = 'UNIDADES'
    cols_valores = ['REMATRICULADO', 'NÃO REMATRICULADO', 'EM TRANSFERENCIA']

    for col in cols_valores:
        df[col] = pd.to_numeric(df[col], errors='coerce').fillna(0)

    # Separar Geral e Unidades
    filtro_geral = df[col_unidade].astype(str).str.contains("GERAL|RESULTADO", case=False, na=False)
    df_geral = df[filtro_geral]
    df_unidades = df[~filtro_geral].dropna(subset=[col_unidade])

    df_final = pd.concat([df_geral, df_unidades])

    # Títulos em Negrito (para usar no subplot_titles)
    titulos_graficos = [f"<b>{u}</b>" for u in df_final[col_unidade]]

    # 2. Configuração do Grid
    num_graficos = len(df_final)
    cols_por_linha = 5
    rows = math.ceil(num_graficos / cols_por_linha)

    specs = [[{'type': 'domain'} for _ in range(cols_por_linha)] for _ in range(rows)]

    fig = make_subplots(
        rows=rows,
        cols=cols_por_linha,
        subplot_titles=titulos_graficos,
        specs=specs,
        # Seus ajustes de espaçamento:
        vertical_spacing=0.12,
        horizontal_spacing=0.01
    )

    # Suas Cores personalizadas (Verde, Vermelho Escuro, Azul)
    cores_fortes = ['#009e0f', '#8e1513', '#004cff']
    labels_legenda = ['Rematriculado', 'Não Rematriculado', 'Em Transferência']

    for i, (index, row) in enumerate(df_final.iterrows()):
        valores = [row[c] for c in cols_valores]
        total_acumulado = sum(valores)

        linha_grid = (i // cols_por_linha) + 1
        coluna_grid = (i % cols_por_linha) + 1
        is_geral = (i == 0) and (not df_geral.empty)

        # Texto Central
        if is_geral:
             texto_centro = f"<span style='font-size:10px; color:#555'>TOTAL</span><br><b style='font-size:18px; color:black'>{int(total_acumulado)}</b>"
        else:
             texto_centro = f"<b style='font-size:14px; color:black'>{int(total_acumulado)}</b>"

        fig.add_trace(go.Pie(
            labels=labels_legenda,
            values=valores,
            name=row[col_unidade],
            hole=0.65,
            marker=dict(colors=cores_fortes, line=dict(color='#ffffff', width=1.5)),

            # Números Externos
            textinfo='value',
            textposition='outside',
            textfont=dict(size=10, family="Arial", color='black'),

            hoverinfo='label+value+percent+name',
            title={
                'text': texto_centro,
                'position': 'middle center',
            },
            showlegend=(i==0)
        ), row=linha_grid, col=coluna_grid)

    # 3. Layout Final (Mantendo suas margens exatas)
    fig.update_layout(
        title_text="<b>PAINEL DE REMATRÍCULAS</b>",
        title_x=0.5,
        title_font=dict(size=22, family="Arial"),
        font=dict(family="Arial", size=11),

        height=240 * rows,

        margin=dict(t=180, b=30, l=30, r=30),

        legend=dict(
            orientation="h",
            yanchor="bottom",
            y=1.10,
            xanchor="center",
            x=0.5,
            font=dict(size=12)
        ),
        template="plotly_white"
    )

    # Ajuste dos Títulos (Seu yshift=24)
    fig.update_annotations(
        font=dict(size=12, family="Arial"),
        yshift=24
    )

    # --- EXIBIÇÃO FINAL NO SITE ---
    st.plotly_chart(fig, use_container_width=True)

else:
    st.warning("Não foi possível carregar os dados. Verifique a planilha.")